version: "3.5"

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
 
  entry_node:
    container_name: entry_node
    image: golang:1.14.4
    entrypoint: /go/bin/main
    command: >
      --config-dir=/tmp
      --database.directory=/tmp/mainnetdb
      --autopeering.seed=base58:8kPPCqaJFAt8BJtx6qw5PN8bKEM2XKXor6PxkmHf6bcr
      --autopeering.entryNodes=
      --analysis.server.bindAddress=0.0.0.0:1888
      --analysis.dashboard.bindAddress=0.0.0.0:9000
      --analysis.dashboard.dev=false
      --analysis.dashboard.mongodb.enabled=true
      --analysis.dashboard.mongodb.hostAddress=mongodb_container:27017
      --metrics.local=false
      --metrics.global=true
      --prometheus.bindAddress=0.0.0.0:9312
      --node.enablePlugins=analysis-server,analysis-dashboard,waspconn
      --node.disablePlugins=portcheck,dashboard,analysis-client,gossip,drng,issuer,syncbeaconfollower,messagelayer,pow,valuetransfers,webapi,webapibroadcastdataendpoint,webapifindtransactionhashesendpoint,webapigetneighborsendpoint,webapigettransactionobjectsbyhashendpoint,webapigettransactiontrytesbyhashendpoint,prometheus
      --database.inMemory=true
    volumes:
      - ./config.docker.json:/tmp/config.json:ro
      - goshimmer-cache:/go
    ports:
      - "127.0.0.1:9000:9000/tcp" # analysis dashboard
    expose:
      - "1888/tcp" # analysis server (within Docker network)

  peer_master:
    container_name: peer_master
    image: golang:1.14.4
    entrypoint: /go/bin/main
    command: >
      --config-dir=/tmp
      --database.directory=/tmp/mainnetdb
      --autopeering.seed=base58:8q491c3YWjbPwLmF2WD95YmCgh61j2kenCKHfGfByoWi
      --node.enablePlugins=spammer,faucet,syncbeacon,waspconn
      --node.disablePlugins=syncbeaconfollower,prometheus
      --faucet.seed=7R1itJx5hVuo9w9hjg5cwKFmek4HMSoBDgJZN8hKGxih
      --faucet.powDifficulty=2
      --valueLayer.snapshot.file=/tmp/assets/7R1itJx5hVuo9w9hjg5cwKFmek4HMSoBDgJZN8hKGxih.bin
      --syncbeacon.broadcastInterval=5
      --syncbeacon.startSynced=true
      --database.inMemory=true
    volumes:
      - ./config.docker.json:/tmp/config.json:ro
      - goshimmer-cache:/go
      - ../integration-tests/assets:/tmp/assets
    ports:
      - "127.0.0.1:8080:8080/tcp" # web API
      - "127.0.0.1:8081:8081/tcp" # dashboard
      - "127.0.0.1:5000:5000/tcp" # waspconn
    depends_on:
      - entry_node

  peer_replica:
    image: golang:1.14.4
    entrypoint: /go/bin/main
    command: >
      --config-dir=/tmp
      --database.directory=/tmp/mainnetdb
      --node.enablePlugins=bootstrap
      --valueLayer.snapshot.file=/tmp/assets/7R1itJx5hVuo9w9hjg5cwKFmek4HMSoBDgJZN8hKGxih.bin
      --node.disablePlugins=portcheck
      --faucet.seed=7R1itJx5hVuo9w9hjg5cwKFmek4HMSoBDgJZN8hKGxih
      --faucet.powDifficulty=2
      --syncbeaconfollower.followNodes=EYsaGXnUVA9aTYL9FwYEvoQ8d1HCJveQVL7vogu6pqCP
      --database.inMemory=true
    volumes:
      - ./config.docker.json:/tmp/config.json:ro
      - goshimmer-cache:/go
      - ../integration-tests/assets:/tmp/assets
    expose:
      - "8080/tcp" # web API (within Docker network)
    depends_on:
      - entry_node

volumes:
  goshimmer-cache:
    name: goshimmer-cache
  mongodb_data_container:
