name: Integration tests

on: pull_request

jobs:

  autopeering:
    name: autopeering
    env:
      TEST_NAME: autopeering
      REMOTE_IMAGE: docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache:${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Branch name 1
        run: echo running on branch1 ${{ github.head_ref }}

      - name: Branch name 2
        run: echo running on branch2 ${{ github.ref }}

      - name: Build GoShimmer image (from cache)
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache:${{ github.head_ref }} || true
          docker build . -t iotaledger/goshimmer --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache:${{ github.head_ref }}
          docker tag iotaledger/goshimmer docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache:${{ github.head_ref }} && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache:${{ github.head_ref }} || true


      - name: Pull additional Docker images
        run: |
          docker pull angelocapossele/drand:1.1.3
          docker pull gaiaadm/pumba:0.7.2
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker-compose -f tools/integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          docker logs tester &> tools/integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_NAME }}
          path: tools/integration-tests/logs


  common:
    name: common
    env:
      TEST_NAME: common
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build GoShimmer image
        run: docker build -t iotaledger/goshimmer .

      - name: Pull additional Docker images
        run: |
          docker pull angelocapossele/drand:1.1.3
          docker pull gaiaadm/pumba:0.7.2
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker-compose -f tools/integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          docker logs tester &> tools/integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_NAME }}
          path: tools/integration-tests/logs

  consensus:
    name: consensus
    env:
      TEST_NAME: consensus
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build GoShimmer image
        run: docker build -t iotaledger/goshimmer .

      - name: Pull additional Docker images
        run: |
          docker pull angelocapossele/drand:1.1.3
          docker pull gaiaadm/pumba:0.7.2
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker-compose -f tools/integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          docker logs tester &> tools/integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_NAME }}
          path: tools/integration-tests/logs


  drng:
    name: drng
    env:
      TEST_NAME: drng
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build GoShimmer image
        run: docker build -t iotaledger/goshimmer .

      - name: Pull additional Docker images
        run: |
          docker pull angelocapossele/drand:1.1.3
          docker pull gaiaadm/pumba:0.7.2
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker-compose -f tools/integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          docker logs tester &> tools/integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_NAME }}
          path: tools/integration-tests/logs



  message:
    name: message
    env:
      TEST_NAME: message
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build GoShimmer image
        run: docker build -t iotaledger/goshimmer .

      - name: Pull additional Docker images
        run: |
          docker pull angelocapossele/drand:1.1.3
          docker pull gaiaadm/pumba:0.7.2
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker-compose -f tools/integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          docker logs tester &> tools/integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_NAME }}
          path: tools/integration-tests/logs



  value:
    name: value
    env:
      TEST_NAME: value
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build GoShimmer image
        run: docker build -t iotaledger/goshimmer .

      - name: Pull additional Docker images
        run: |
          docker pull angelocapossele/drand:1.1.3
          docker pull gaiaadm/pumba:0.7.2
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker-compose -f tools/integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          docker logs tester &> tools/integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_NAME }}
          path: tools/integration-tests/logs

  faucet:
    name: faucet
    env:
      TEST_NAME: faucet
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build GoShimmer image
        run: docker build -t iotaledger/goshimmer .

      - name: Pull additional Docker images
        run: |
          docker pull angelocapossele/drand:1.1.3
          docker pull gaiaadm/pumba:0.7.2
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker-compose -f tools/integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          docker logs tester &> tools/integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_NAME }}
          path: tools/integration-tests/logs

  syncbeacon:
    name: syncbeacon
    env:
      TEST_NAME: syncbeacon
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build GoShimmer image
        run: docker build -t iotaledger/goshimmer .

      - name: Pull additional Docker images
        run: |
          docker pull angelocapossele/drand:1.1.3
          docker pull gaiaadm/pumba:0.7.2
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker-compose -f tools/integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          docker logs tester &> tools/integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_NAME }}
          path: tools/integration-tests/logs
