name: Snyk test dependencies

on: 
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  security:
    runs-on: ubuntu-latest
    # Only run on push events or PRs from iotaledger/goshimmer, skip on PRs from forks
    # Secret variables cannot be exposed to PRs from forks
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
    - uses: actions/checkout@master

    - name: Run Snyk to test dependencies
      uses: snyk/actions/golang@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --org=iota-foundation
